name: teamspeakclientlib
description: A starting point for Dart libraries or applications.
version: 0.0.0-dev.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  async: ^2.9.0
  either_option: ^2.0.0
  tuple: ^2.0.0
  quiver: ^3.1.0
  convert: ^3.0.2
  path: ^1.8.2
  logging: ^1.0.2
  stream_channel: ^2.1.1
  dio: ^4.0.6
  toml: ^0.13.1
  quicklz_ffi:
    git: https://github.com/kjzl/quicklz_ffi.git
  pointycastle:
    git: https://github.com/kjzl/pc-dart-eax.git
  source_gen: ^1.2.5
  build: ^2.3.1
  build_config: ^1.1.0
  json_annotation: ^4.7.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.6
  json_serializable: ^6.4.0
  build_runner: ^2.2.1
